### ISSUE TITLE
Add functionality to save filters or disable them

### ISSUE THREAD

**Issue by IbakonFerba** [XDargu/FrameByFrame#109]
When I create a filter currently, it is always active. I can hide or unhide the results of the filter, but if I want to get rid of the filtering I have to delete the filter. If I want to filter again, I have to recreate the filter.
It would be good if I could either save and load filters, or (and I would prefer this) disable existing filters without deleting them

**Comment by XDargu** [comment]
I'm adding the option to export & import filters.
Also, you can create an empty event filter to simulate having no filters. What Frame by Frame does by default is exactly that: create an empty event filter. This is why all events are displayed on the timeline by default.
