### ISSUE TITLE
Feature request: auto record buffer X seconds

### ISSUE THREAD

**Issue by dacaes** [XDargu/FrameByFrame#118]
Option to enable FbF to automatically record and keep a buffer of X (e.g. 60) seconds.

As users can be sure the previous 60 seconds are always recorded, they can press record just when they see something weird start to happen. It avoids the typical situation when something you wanted to record happens before pressing the record button.

Extra: Button to save clip. Quick saves a clip with the current buffered record.

**Comment by XDargu** [comment]
With the feature of deleting old frames in #119, this is now possible. Just keep FbF connected while playing/working, and enable the removal of old frames. When you see an issue, pause the recording. The past N frames (depending on the configured amount in settings) should be available.
